# Generated by Django 5.2 on 2025-04-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=40, null=True)),
                ('image', models.CharField(max_length=40, null=True)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
